# vim: set ts=2 sw=2 et :
---

- name: Install Extra Performance Co-Pilot Packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - pcp-pmda-dm
  - pcp-pmda-gluster

- name: Open firewall for PCP
  firewalld:
    service: pmcd
    state: enabled
    immediate: true
    permanent: true

- name: Install additional pmda(s)
  shell: "echo b | ./Install"
  args:
    chdir: "/var/lib/pcp/pmdas/{{ item }}"
  with_items:
  - dm

- name: Install Gluster pmda only on master nodes
  shell: "echo b | ./Install"
  args:
    chdir: "/var/lib/pcp/pmdas/gluster"
  when: group_names|join(" ") is search("tag_gluster_master")
