- name: Make sure cluster_master is up
  ping:
  delegate_to: "{{ cluster_master }}"
  run_once: true

- name: Check for required variables
  fail: msg="Variable {{ item }} must be defined to use this playbook"
  when: item is undefined
  with_items:
  - cluster_master
  - volume
  - gluster_volumes
  - gluster_volumes[volume].device
  - gluster_volumes[volume].group
  - gluster_volumes[volume].size

- name: Check for existing volume
  command: "gluster volume list"
  delegate_to: "{{ cluster_master}}"
  run_once: true
  register: vol_list
  changed_when: false

- name: Create volume
  include_tasks: "mk_volume.yml"
  when: "volume not in vol_list.stdout"
