# vim: set ts=2 sw=2 et :
---

- name: Validation
  hosts: localhost
  become: false
  tasks:
  - name: Check for required variables
    fail: msg="Variable {{ item }} must be defined to use this playbook"
    when: item not in vars
    with_items:
    - volume_name
    - size
    - device
    - server_group


- name: Make Gluster brick
  hosts: "{{ server_group }}"
  become: true
  tasks:
  - name: Create volume group
    lvg:
      pvs: "{{ device }}"
      vg: "{{ volume_name }}"

  - name: Create thin pool
    command: "lvcreate --thin {{ volume_name }}/pool
                       -l 100%FREE
                       --chunksize 256k
                       --poolmetadatasize 16G
                       --zero n"
    args:
      creates: "/dev/mapper/{{ volume_name }}-pool"

  - name: Create brick LV
    command: "lvcreate --thin
                       --name {{ volume_name }}
                       --virtualsize {{ size }}
                       {{ volume_name }}/pool"
    args:
      creates: "/dev/mapper/{{ volume_name }}-{{ volume_name }}"

  - name: Create brick file system
    filesystem:
      dev: "/dev/mapper/{{ volume_name }}-{{ volume_name }}"
      fstype: xfs
      opts: -i size=512

  - name: Create brick mount directory
    file:
      path: "/bricks/{{ volume_name }}"
      state: directory

  - name: Mount brick
    mount:
      fstype: xfs
      opts: inode64
      path: /bricks/{{ volume_name }}
      src: /dev/mapper/{{ volume_name }}-{{ volume_name }}
      state: mounted

  - name: Create brick root directory
    file:
      path: "/bricks/{{ volume_name }}/brick"
      state: directory



- name: Create volume
  hosts: "{{ server_group[0] }}"
  become: true
  tasks:
  - name: Create volume
    command: "gluster volume create {{ volume_name }} replica 3
              {{ server_group | map('extract', hostvars, 'ansible_fqdn') |
                 map('regex_replace', '(.+)', '\\1:/bricks/XXXXX/brick') |
                 map('regex_replace', 'XXXXX', volume_name) | join (' ') }}"

  - name: Enable data encryption (client)
    command: gluster volume set {{ volume_name }} client.ssl on

  - name: Enable data encryption (server)
    command: gluster volume set {{ volume_name }} server.ssl on

  - name: Start volume
    command: gluster volume start {{ volume_name }}
