# vim: set ts=2 sw=2 et :
---

- name: Prepare Gluster TLS CA
  hosts: localhost
  become: false
  roles:
  - prepare-gluster-ca

- name: Install Gluster servers
  hosts: gluster-servers
  become: true
  roles:
  - gluster-server
  - gluster-client
  - gluster-tls-generate
  - gluster-server-stop
  - gluster-tls-enable
  - gluster-server-start

- name: Clean up local TLS files
  hosts: localhost
  become: false
  tasks:
  - name: Clean up local temp directory
    file:
      path: "{{ hostvars.localhost.tempdir }}"
      state: absent

  # Use the 1st storage node to establish the cluster
- name: Initialize Gluster TSP
  hosts: "{{ groups['gluster-servers'][0] }}"
  become: true
  tasks:
    - name: Establish TSP
      # Make sure we use Amazon's internal fqdn for the servers
      command: gluster peer probe {{ hostvars[item]['ansible_fqdn'] }}
      with_items: "{{ groups['gluster-servers'] }}"
