# vim: set ts=2 sw=2 et :
---

- name: Register machine
  hosts: all
  become: true
  vars_prompt:
  - name: rhsm_user
    prompt: "access.redhat.com username"
  - name: rhsm_pass
    prompt: "access.redhat.com password"
  tasks:
  - name: Register w/ subscription-manager
    redhat_subscription:
      username: "{{ rhsm_user }}"
      password: "{{ rhsm_pass }}"
      state: present
      # Employee sku
      pool_ids:
      - 8a85f9815ad3324a015ad3b083e545b3

  - name: Disable all repos
    command: subscription-manager repos --disable='*'

  - name: Enable repos
    command: "subscription-manager repos --enable='{{ item }}'"
    with_items:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rh-gluster-3-for-rhel-7-server-rpms

  - include_role:
      name: update-system

  - include_role:
      name: reboot-system
    when: system_updated.changed == true
