# vim: set ts=2 sw=2 et :
---

- hosts: all
  become: false
  gather_facts: false
  tasks:
  # Sometimes provisioning starts before all hosts are up and ready,
  # causing failures. Here, we delay until we can ansible ping
  - name: Wait for host to be available
    ping:
      data: "pong"
    register: task_result
    until: task_result.ping == "pong"
    delay: 2
    retries: 60
    changed_when: false

- hosts: all
  become: true
  tasks:
  # AWS attaches disks to /dev/xvd*, but vagrant /dev/vd*
  # Symlinking allows us to use the same playbooks on both
  # This creates a udev rule to do that for us!
  - name: Create /dev/vd* ==> /dev/xvd* udev rule
    copy:
      content: 'KERNEL=="vd[a-z]*", SUBSYSTEM=="block", SYMLINK+="x%k"'
      dest: /etc/udev/rules.d/90-hdd-links.rules
    register: udev_hdd_rule

  - name: Reload udev rules
    command: "udevadm control --reload"
    when: udev_hdd_rule.changed

  - name: Trigger udev events
    command: "udevadm trigger"
    when: udev_hdd_rule.changed
