---
# vim: set ts=2 sw=2 et :

- name: Install libsemanage-python to manage SELinux
  package:
    name: libsemanage-python
    state: latest

- name: Install Gluster server packages
  package:
    name: redhat-storage-server
    state: latest
  register: rhgs_updated

- name: Reboot if packages were updated
  include_role:
    name: reboot-system
  when: rhgs_updated.changed == true

# Need to configure iptables here
# iptables default is open

  # Fix problem where rpcbind won't start w/ disabled IPv6
  # https://bugzilla.redhat.com/show_bug.cgi?id=1402961
#- name: Rebuild initramfs
#  command: dracut -f

  # Fix problem where rpcbind won't start first time
  # https://bugzilla.redhat.com/show_bug.cgi?id=1474593
#- name: Temporarily switch SELinux to Permissive
#  selinux:
#    policy: targeted
#    state: permissive

- name: Enable & start Gluster
  systemd:
    daemon_reload: yes
    name: glusterd
    enabled: yes
    state: started

#- name: Switch SELinux back to Enforcing
#  selinux:
#    policy: targeted
#    state: enforcing
