---
# vim: set ts=2 sw=2 et :

- name: Enable repos
  command: "subscription-manager repos --enable='{{ item }}'"
  with_items:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rh-gluster-3-for-rhel-7-server-rpms

- name: Install Gluster server packages
  package:
    name: redhat-storage-server
    state: latest
  register: rhgs_updated

- name: Start firewalld
  systemd:
    daemon_reload: true
    name: firewalld
    enabled: true
    state: started

- name: Open firewall for Gluster
  firewalld:
    service: glusterfs
    state: enabled
    immediate: true
    permanent: true

- include_role:
    name: gluster-enable-tls

- name: Enable Glusterd
  systemd:
    daemon_reload: true
    name: glusterd
    enabled: true
    state: stopped

- name: Enable systemd to auto-restart glusterd
  lineinfile:
    state: present
    insertafter: "^\\[Service\\]"
    # Ensure only 1 key= instance exists, and only match left of equal
    # so we can change the value, too
    regexp: "{{ item | regex_search('^(.*=)') }}"
    line: "{{ item }}"
    path: /usr/lib/systemd/system/glusterd.service
  with_items:
    - "RestartSec=60"
    - "Restart=on-abnormal"
    # Old setting name for interval
    - "StartLimitInterval=3600"
    # New setting name for interval
    - "StartLimitIntervalSec=3600"
    - "StartLimitBurst=3"

- name: start Glusterd
  systemd:
    daemon_reload: true
    name: glusterd
    state: started

- name: Add daily fstrim of filesystems
  lineinfile:
    create: yes
    regexp: 'fstrim'
    line: "55 23 * * * root /usr/sbin/fstrim -a"
    path: /etc/cron.d/fstrim-devices
    state: present

- name: Install additional packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - screen
