---
# vim: set ts=2 sw=2 et :

- name: Install Gluster server packages
  package:
    name: redhat-storage-server
    state: latest
  register: rhgs_updated

- name: Open firewall for Gluster
  firewalld:
    service: glusterfs
    state: enabled
    immediate: true
    permanent: true

- include_role:
    name: gluster-enable-tls

- name: Enable & start Gluster
  systemd:
    daemon_reload: yes
    name: glusterd
    enabled: yes
    state: started
