---
# vim: set ts=2 sw=2 et :

- name: Enable repos
  command: "subscription-manager repos --enable='{{ item }}'"
  with_items:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rh-gluster-3-for-rhel-7-server-rpms

- name: Install Gluster server packages
  package:
    name: redhat-storage-server
    state: latest
  register: rhgs_updated

- name: Start firewalld
  systemd:
    daemon_reload: yes
    name: firewalld
    enabled: true
    state: started

- name: Open firewall for Gluster
  firewalld:
    service: glusterfs
    state: enabled
    immediate: true
    permanent: true

- include_role:
    name: gluster-enable-tls

- name: Enable & start Gluster
  systemd:
    daemon_reload: yes
    name: glusterd
    enabled: true
    state: started

- name: Install additional packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - git
  - screen
