---
# vim: set ts=2 sw=2 et :

- name: Sync file system
  command: sync
  changed_when: false

- name: Reboot server
  shell: sleep 2 && systemctl reboot
  async: 1
  poll: 0

- name: Wait for host to be available after reboot
  wait_for_connection:
    delay: 15
