# vim: set ts=2 sw=2 et :
---

# In addition to limiting where this runs via -l <hosts/groups>, you can use
# -e only_volumes=myvol to only execute against a specific set of volumes

- hosts: gluster-servers
  become: true
  any_errors_fatal: true
  tasks:
  - include_role:
      name: gluster-subvol
    with_items: "{{ gluster_volumes }}"
    when: "gluster_volumes is defined and
           inventory_hostname in groups[gluster_volumes[volume].group] and
           (only_volumes is not defined or volume in only_volumes)"
    loop_control:
      loop_var: volume
