# vim: set ts=2 sw=2 et :
---

- name: Install Gluster on servers
  hosts: gluster-servers
  become: true
  roles:
  - gluster-server
  - pcp-collector


- name: Install Gluster client everywhere
  hosts: all
  become: true
  roles:
  - gluster-client
