# vim: set ts=2 sw=2 et :
---

- name: Secure gluster shared storage volume
  hosts: gluster-servers
  become: true
  any_errors_fatal: true
  tasks:
  - include_role:
      name: gluster-secure-shared-storage
    with_items: "{{ cluster_member_group }}"
    when: "cluster_member_group is defined and
           inventory_hostname in groups[member_group]"
    loop_control:
      loop_var: member_group
