# vim: set ts=2 sw=2 et :
---

# This playbook will upgrade a set of hosts using `yum update`. It will update
# all packages to their latest version. As a part of the upgrade, it will:
# - Upgrades will be done 1 node at a time
# - For Gluster servers, there are pre-flight and post-upgrade checks to wait
#   for the cluster/volumes to heal
# - If gluster packages are being updated, it will stop Gluster on the node
# - If any packages are updated, the node will be rebooted
#
# Whole gluster clusters should be updated in a single run of the playbook to
# ensure it can properly call out to the "cluster_master" for gluster
# operations.

- hosts: all
  become: true
  any_errors_fatal: true
  tasks:
    # During upgrade, we need to disable the xfs brick quotas to ensure volumes
    # can properly heal
    - name: Get list of brick directories with quota
      shell: "xfs_quota -x -c 'state -p' | sed -nE 's|.*(/bricks/\\S+).*|\\1|p'"
      register: dir_quota_list
      changed_when: false

    - name: Disable project quota enforcement
      shell: "xfs_quota -x -c 'disable -pv' {{ item }}"
      with_items: "{{ dir_quota_list.stdout_lines }}"

    # Upgrade one host at a time
    - include_role:
        name: upgrade
      with_items: "{{ play_hosts }}"
      when: "hostvars[upgrading_host].inventory_hostname == inventory_hostname"
      loop_control:
        loop_var: upgrading_host

    - name: Enable project quota enforcement
      shell: "xfs_quota -x -c 'enable -pv' {{ item }}"
      with_items: "{{ dir_quota_list.stdout_lines }}"
