---
# vim: set ts=2 sw=2 et :

- name: Make sure /var/lib/glusterd exists
  file:
    path: /var/lib/glusterd/
    state: directory

- name: Enable management TLS
  file:
    path: /var/lib/glusterd/secure-access
    state: touch
